export * from './AutoApi';
import { AutoApi }  from './AutoApi';
export * from './CatalogApi';
import { CatalogApi }  from './CatalogApi';
export * from './GlobalApi';
import { GlobalApi }  from './GlobalApi';
export * from './ImportationCatalogInfoApi';
import { ImportationCatalogInfoApi }  from './ImportationCatalogInfoApi';
export * from './ImportationProcessApi';
import { ImportationProcessApi }  from './ImportationProcessApi';
export const APIS = [ AutoApi, CatalogApi, GlobalApi, ImportationCatalogInfoApi, ImportationProcessApi, ];
