/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The different actions you can make on this account
 */
export interface AccountInfoLinks {
    "savePersonalInfo": models.LinksSavePersonalInfoLink;
    "changePassword": models.LinksChangePasswordLink;
    "saveCompanyInfo": models.LinksSaveCompanyInfoLink;
    "getProfilePictureInfo": models.LinksGetProfilePictureInfoLink;
    "saveProfilePictureInfo": models.LinksSaveProfilePictureInfoLink;
    "getCreditCardInfo": models.LinksGetCreditCardInfoLink;
    "saveCreditCardInfo": models.LinksSaveCreditCardInfoLink;
}

