/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Your api credential
 */
export interface ApiCredential {
    /**
     * The product name related to this credential
     */
    "productName"?: string;
    /**
     * The primary token to be used in the next call in the user scope API
     */
    "primaryToken"?: string;
    /**
     * The secondary token. Could be usefull if you want to share your access with someone else.
     */
    "secondaryToken"?: string;
}

