/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BeezUPCommonLinkParameter3 {
    /**
     * The value of the parameter. It can be an integer a string or an object.
     */
    "value"?: any;
    "required"?: boolean;
    "in": models.BeezUPCommonParameterIn;
    "type"?: models.BeezUPCommonParameterType;
    "lovLink"?: models.BeezUPCommonLOVLink3;
    /**
     * If true, you MUST indicate a value from the list of values otherwise it's a freetext
     */
    "lovRequired"?: boolean;
    /**
     * description of the parameter
     */
    "description"?: string;
    /**
     * schema of the parameter
     */
    "schema"?: string;
    /**
     * If the parameter is an object with flexible properties (additionProperties/dictionary), we will describe the properties of the object.
     */
    "properties"?: { [key: string]: models.BeezUPCommonLinkParameterProperty3; };
}

