/**
 * Public - Security
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BeezUPCommonLinkParameter2 {
    /**
     * The name of the parameter
     */
    "name": string;
    /**
     * The value of the parameter
     */
    "value"?: string;
    "required"?: boolean;
    "in"?: models.BeezUPCommonParameterIn;
    "type"?: models.BeezUPCommonParameterType;
    /**
     * This parameter expect the values indicated in this list of values.
     */
    "lovLink"?: models.BeezUPCommonLOVLink2;
    /**
     * If true, you MUST use indicate a value from the list of values otherwise it's a freetext
     */
    "lovRequired"?: boolean;
}

