/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ChannelCatalogMarketplaceProperty {
    /**
     * Channel catalog marketplace property name
     */
    "name": string;
    /**
     * Channel catalog marketplace property values
     */
    "values"?: Array<string>;
    "info"?: models.BeezUPCommonInfoSummaries;
    /**
     * Indicate the default values of the property
     */
    "default"?: Array<string>;
    /**
     * Indicate the description of the property
     */
    "description"?: string;
    /**
     * Indicate the position of the property in the display group
     */
    "position": number;
    /**
     * Indicate if the value cannot be changed. This is used for example for ebay token that should not be changed.
     */
    "readOnly": boolean;
    /**
     * Indicates the minimum size of the property value
     */
    "minLength"?: number;
    /**
     * Indicates the maximum size of the property value
     */
    "maxLength"?: number;
    /**
     * Indicates the minimum item count of the property value.
     */
    "minItems"?: number;
    /**
     * Indicates the maximum item count of the property value
     */
    "maxItems"?: number;
    "lovLink"?: models.BeezUPCommonLOVLink3;
    /**
     * Indicates if the property value must be in the list of value.
     */
    "lovRequired"?: boolean;
    /**
     * Indicate if the property is required or not
     */
    "required": boolean;
    /**
     * Indicates the offer identifier required to configure this property.
     */
    "offerIdRequired"?: number;
    /**
     * Indicates if this property should be displayed in the configuration page.
     */
    "visible": boolean;
    "type"?: models.Type;
    /**
     * Channel catalog marketplace setting value format validation regular expression
     */
    "pattern"?: string;
}

