/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ChannelCatalogMarketplacePropertyGroup {
    /**
     * Indicate the code identifier of the group
     */
    "displayGroupCode": string;
    /**
     * Indicate the position of the group
     */
    "displayGroupPosition": number;
    "properties": Array<models.ChannelCatalogMarketplaceProperty>;
}

