/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The reporting related to a change order operation
 */
export interface ChangeOrderReporting {
    "executionUUID"?: models.ExecutionUUID;
    "changeOrderType"?: models.BusinessOperationType;
    "sourceType"?: models.SourceType;
    "sourceUserId"?: models.BeezUPCommonUserId;
    "sourceUserName"?: string;
    /**
     * The creation UTC date of the execution
     */
    "creationUtcDate"?: Date;
    /**
     * The processing status of the execution
     */
    "processingStatus"?: string;
    /**
     * The last update UTC date of the execution
     */
    "lastUpdateUtcDate"?: Date;
    /**
     * The error message during the execution
     */
    "errorMessage"?: string;
    /**
     * The IP address who request this operation
     */
    "ipAddress"?: string;
    /**
     * This operation was a test
     */
    "testMode"?: boolean;
    "details"?: { [key: string]: any; };
}

