/**
 * Public - Security
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Describe the commitment information related to the offer.
 */
export interface ContractCommitmentInfo {
    /**
     * The commitment end date related to the offer
     */
    "commitmentCalculatedFinishDate"?: Date;
    /**
     * The start date related to the offer
     */
    "newContractStartDate"?: Date;
    /**
     * The commitment period in month related to the offer
     */
    "commitmentPeriodInMonth"?: number;
    /**
     * The trial period in month related to the offer
     */
    "trialPeriodInMonth"?: number;
    /**
     * The trial period end date related to the offer
     */
    "trialPeriodFinishDate"?: Date;
    /**
     * The payment delay in days related to the offer
     */
    "paymentDelayInDays"?: number;
    "offerId"?: models.OfferId;
    /**
     * The offer Name
     */
    "offerName"?: string;
    /**
     * Your current contract id
     */
    "currentContractId"?: string;
    /**
     * Your current commercial user id
     */
    "commercialUserId"?: string;
    /**
     * Interal usage: Old offer type. The model description
     */
    "model"?: string;
    /**
     * The current contract termination date
     */
    "currentContractTerminationDate"?: Date;
    "requestedPaymentMethod"?: models.PaymentMethod;
    "currentCustomerPaymentMethod"?: models.PaymentMethod;
    /**
     * Internal usage: Old offer type. Your contract type
     */
    "contractType"?: number;
    /**
     * Internal usage: Old offer type. Is the current contract model needs to be converted into a new contract type
     */
    "isModelMustBeTransmittedInNewContract"?: boolean;
    "fixedAndVariableClickInfo"?: models.FixedAndVariableClickModelInfo;
    "variableModelInfo"?: models.VariableModelInfo;
    "paymentMethodAuthorized"?: models.PaymentMethod;
    "couponOfferCode"?: models.CouponOfferCode;
    /**
     * The commercial that is responsible of the creation of your account
     */
    "commercialCreatorUserId"?: string;
    /**
     * The minimum billing period in month authorized for this offer.
     */
    "minBillingPeriodInMonths"?: number;
    /**
     * If true, this means you want to leave us and that's sad... :'-(
     */
    "isCustomerWantsToTerminateHisContract"?: boolean;
}

