/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The exclusion filter
 */
export interface ExclusionFilter {
    "name": models.ExclusionFilterName;
    /**
     * The position of the exclusion filter
     */
    "position": number;
    /**
     * Indicate the filter's group. All filters in the same group means an \"AND\" operation in the filter group
     */
    "groupId": string;
    /**
     * Indicate the filter group position. This information is used for the UI purpose and must be unique in the filter group.
     */
    "positionInGroup": number;
    "channelColumnId": models.BeezUPCommonChannelColumnId;
    "operatorName": models.ExclusionFilterOperatorName;
    /**
     * The value indicate by the user when the filter operation requires it.
     */
    "value"?: string;
    /**
     * indicates if the filter is currently active.
     */
    "enabled": boolean;
}

