/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * In case your catalog column already exists we indicate you the existing configuration.
 */
export interface ExistingCatalogColumnConfiguration {
    "userColumName": models.UserColumName;
    "configuration": models.ColumnConfiguration;
}

