/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The message request to export order list. The store identifier is requested to regroup the exportations.
 */
export interface ExportOrderListRequest {
    "format"?: models.ExportOrderListFormat;
    "storeId": models.BeezUPCommonStoreId;
    "orderListRequest": models.OrderListRequest;
}

