/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Describe how to read the file. If FileFormatStrategy is CSV, csvFileReadProperties is required. Otherwise the xmlFileReadProperties is required. 
 */
export interface InputFileReadConfiguration {
    "format": models.FileFormatStrategy;
    /**
     * The encoding type. UTF-8 by default.
     */
    "encodingTypeName"?: string;
    /**
     * The culture name of the file.  (i.e. fr-FR). If null then Invariant culture will be used.
     */
    "cultureName"?: string;
    "csvFileReadProperties"?: models.InputFileReadCsvConfiguration;
    "xmlFileReadProperties"?: models.InputFileReadXmlConfiguration;
}

