/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Invoice {
    /**
     * The invoice date
     */
    "invoiceDate": Date;
    "contractId": models.ContractId;
    "invoiceNumber": models.InvoiceNumber;
    /**
     * The amount of your invoice
     */
    "amount": number;
    /**
     * The remaining amount to be paid for this invoice
     */
    "amountToBePaid": number;
    "currencyCode": models.BeezUPCommonCurrencyCode;
    "paymentStatus": models.InvoicePaymentStatus;
    "dueDate": Date;
    /**
     * The url of the invoice document
     */
    "invoiceUrl"?: string;
}

