/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Describe the history related to an order
 */
export interface OrderHistory {
    /**
     * The list of change order operation
     */
    "changeOrderReportings"?: Array<models.ChangeOrderReporting>;
    "harvestOrderReportings"?: Array<models.HarvestOrderReporting>;
    "lastModificationUtcDate"?: Date;
    "info"?: models.BeezUPCommonInfoSummaries;
}

