/**
 * Public - Security
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Gives you all entry point operations you can do on this API
 */
export interface OrderIndexLinks {
    "self": models.LinksGetOrderIndexLink;
    "status": models.LinksGetMarketplaceAccountsSynchronizationLink;
    "harvest": models.LinksHarvestAllLink;
    "setMerchantInfos": models.LinksSetMerchantOrderInfoListLink;
    "clearMerchantInfos": models.LinksClearMerchantOrderInfoListLink;
    "export": models.LinksExportOrdersLink;
    "autoTransitions": models.LinksGetAutomaticTransitionsLink;
    "exportations"?: models.LinksGetOrderExportationsLink;
    "orders": models.LinksGetOrderListFullLink;
    "lightOrders": models.LinksGetOrderListLightLink;
}

