/**
 * Public - Security
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Gives you all the LOV to get the translations realated to operation name, codes, property names and statuses.
 */
export interface OrderIndexLovLinks {
    "orderChangeBusinessOperationType": models.BeezUPCommonLOVLink3;
    "orderState": models.BeezUPCommonLOVLink3;
    "orderProperty": models.BeezUPCommonLOVLink3;
    "orderPropertyPosted": models.BeezUPCommonLOVLink3;
}

