/**
 * BeezUP API
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The order list with minimum information we have from the orders.\\ The paginationResult properties can be null if the list is empty.  
 */
export interface OrderListLight {
    "paginationResult"?: models.BeezUPCommonPaginationResult;
    "orders": Array<models.OrderHeader>;
    "links": models.OrderListLightLinks;
}

