/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The list of actions you can do from the order list response
 */
export interface OrderListLinks {
    "harvest": models.LinksHarvestAllLink;
    "setMerchantInfos": models.LinksSetMerchantOrderInfoListLink;
    "clearMerchantInfos": models.LinksClearMerchantOrderInfoListLink;
    "export": models.LinksExportOrdersLink;
    "status": models.LinksGetMarketplaceAccountsSynchronizationLink;
}

