/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ReportByDayAllChannels {
    /**
     * The click count for this channel
     */
    "clickCount": number;
    /**
     * The cost for this channel
     */
    "cost": number;
    /**
     * The order count for this channel
     */
    "orderCount": number;
    /**
     * The Turnover for this channel
     */
    "turnOver": number;
    /**
     * The margin for this channel
     */
    "margin": number;
    /**
     * The performance indicator based on the performance indicator formula indicated in the request for this channel
     */
    "performanceIndicator": number;
}

