/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Links to retrieve/action on other entities
 */
export interface RuleLinks {
    "self"?: models.DefinitionslinksGetRuleLink;
    "run"?: models.DefinitionslinksRunRuleLink;
    "delete"?: models.DefinitionslinksDeleteRuleLink;
    "moveup"?: models.DefinitionslinksMoveUpRuleLink;
    "movedown"?: models.DefinitionslinksMoveDownRuleLink;
    "enable"?: models.DefinitionslinksEnableRuleLink;
    "disable"?: models.DefinitionslinksDisableRuleLink;
    "update"?: models.DefinitionslinksUpdateRuleLink;
    "reportFilter"?: models.DefinitionslinksGetReportFilterLink;
}

