/**
 * Public - Security
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Rule {
    /**
     * The identifier of the rule
     */
    "ruleId": string;
    /**
     * The name of the rule
     */
    "ruleName": string;
    "lastExecutionStatus"?: models.RuleLastExecutionStatus;
    /**
     * The utc date of the last execution
     */
    "lastExecutionUtcDate"?: Date;
    "actionName": models.OptimisationActionName;
    /**
     * Report filter identifier linked to the rule
     */
    "reportFilterId": string;
    /**
     * Rule execution position
     */
    "position": number;
    /**
     * Is the rule enabled
     */
    "enabled": boolean;
    /**
     * Rule validity start utc date
     */
    "validityStartUtcDate"?: Date;
    /**
     * Rule validity end utc date
     */
    "validityEndUtcDate"?: Date;
    "links": models.RuleLinks;
}

