/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The message request to schedule the auto import
 */
export interface ScheduleAutoImportRequest {
    /**
     * Indicate the time span you want to import your catalog. (i.e. \"21:00:00\" to import your catalog at 9PM)
     */
    "schedules": Array<string>;
    /**
     * If null the local time zone name will be \"Romance Standard Time\"
     */
    "localTimeZoneName"?: string;
}

