/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The store status * Active:  When the store is active * SystemBlocked:  When the store is blocked by the system * UserBlocked: When the store is blocked on GO not on the system * NotActivated: When the email is not verified 
 */
export interface StoreStatus {
}

