import * as api from './api/api';
import * as angular from 'angular';

const apiModule = angular.module('api', [])
.service('AccountApi', api.AccountApi)
.service('AlertsApi', api.AlertsApi)
.service('AutoApi', api.AutoApi)
.service('AutoTransitionsApi', api.AutoTransitionsApi)
.service('BatchesApi', api.BatchesApi)
.service('CatalogApi', api.CatalogApi)
.service('ChannelCatalogsCategoryMappingsApi', api.ChannelCatalogsCategoryMappingsApi)
.service('ChannelCatalogsColumnMappingsApi', api.ChannelCatalogsColumnMappingsApi)
.service('ChannelCatalogsExclusionFiltersApi', api.ChannelCatalogsExclusionFiltersApi)
.service('ChannelCatalogsGlobalApi', api.ChannelCatalogsGlobalApi)
.service('ChannelCatalogsProductsApi', api.ChannelCatalogsProductsApi)
.service('ChannelCatalogsProductsOptimisationApi', api.ChannelCatalogsProductsOptimisationApi)
.service('ChannelCatalogsProductsOverridesApi', api.ChannelCatalogsProductsOverridesApi)
.service('ChannelCatalogsSettingsApi', api.ChannelCatalogsSettingsApi)
.service('ChannelsGlobalApi', api.ChannelsGlobalApi)
.service('ContractsApi', api.ContractsApi)
.service('ExportsApi', api.ExportsApi)
.service('FriendsApi', api.FriendsApi)
.service('GlobalApi', api.GlobalApi)
.service('GroupsApi', api.GroupsApi)
.service('ImportationCatalogInfoApi', api.ImportationCatalogInfoApi)
.service('ImportationProcessApi', api.ImportationProcessApi)
.service('InvoicesApi', api.InvoicesApi)
.service('LOVApi', api.LOVApi)
.service('ListApi', api.ListApi)
.service('MarketplacesChannelCatalogsGlobalApi', api.MarketplacesChannelCatalogsGlobalApi)
.service('MarketplacesChannelCatalogsPublicationsApi', api.MarketplacesChannelCatalogsPublicationsApi)
.service('MarketplacesChannelCatalogsSettingsApi', api.MarketplacesChannelCatalogsSettingsApi)
.service('OneOrderApi', api.OneOrderApi)
.service('OptimisationsApi', api.OptimisationsApi)
.service('ReportsApi', api.ReportsApi)
.service('RightsApi', api.RightsApi)
.service('RulesApi', api.RulesApi)
.service('SecurityApi', api.SecurityApi)
.service('SharesApi', api.SharesApi)
.service('StoresApi', api.StoresApi)
.service('TrackingApi', api.TrackingApi)

export default apiModule;
