import * as api from './api/api';
import * as angular from 'angular';

const apiModule = angular.module('api', [])
.service('AnalyticsOptimisationsApi', api.AnalyticsOptimisationsApi)
.service('AnalyticsReportsApi', api.AnalyticsReportsApi)
.service('AnalyticsRulesApi', api.AnalyticsRulesApi)
.service('AnalyticsTrackingApi', api.AnalyticsTrackingApi)
.service('CatalogsAutoApi', api.CatalogsAutoApi)
.service('CatalogsCatalogApi', api.CatalogsCatalogApi)
.service('CatalogsGlobalApi', api.CatalogsGlobalApi)
.service('CatalogsImportationCatalogInfoApi', api.CatalogsImportationCatalogInfoApi)
.service('CatalogsImportationProcessApi', api.CatalogsImportationProcessApi)
.service('ChannelCatalogsCategoryMappingsApi', api.ChannelCatalogsCategoryMappingsApi)
.service('ChannelCatalogsColumnMappingsApi', api.ChannelCatalogsColumnMappingsApi)
.service('ChannelCatalogsExclusionFiltersApi', api.ChannelCatalogsExclusionFiltersApi)
.service('ChannelCatalogsExportationsApi', api.ChannelCatalogsExportationsApi)
.service('ChannelCatalogsGlobalApi', api.ChannelCatalogsGlobalApi)
.service('ChannelCatalogsProductsApi', api.ChannelCatalogsProductsApi)
.service('ChannelCatalogsProductsOptimisationApi', api.ChannelCatalogsProductsOptimisationApi)
.service('ChannelCatalogsProductsOverridesApi', api.ChannelCatalogsProductsOverridesApi)
.service('ChannelCatalogsSettingsApi', api.ChannelCatalogsSettingsApi)
.service('ChannelsChannelsGlobalApi', api.ChannelsChannelsGlobalApi)
.service('CustomerAccountApi', api.CustomerAccountApi)
.service('CustomerAlertsApi', api.CustomerAlertsApi)
.service('CustomerContractsApi', api.CustomerContractsApi)
.service('CustomerFriendsApi', api.CustomerFriendsApi)
.service('CustomerInvoicesApi', api.CustomerInvoicesApi)
.service('CustomerRightsApi', api.CustomerRightsApi)
.service('CustomerSecurityApi', api.CustomerSecurityApi)
.service('CustomerSharesApi', api.CustomerSharesApi)
.service('CustomerStoresApi', api.CustomerStoresApi)
.service('MarketplacesChannelCatalogsGlobalApi', api.MarketplacesChannelCatalogsGlobalApi)
.service('MarketplacesChannelCatalogsPublicationsApi', api.MarketplacesChannelCatalogsPublicationsApi)
.service('MarketplacesChannelCatalogsSettingsApi', api.MarketplacesChannelCatalogsSettingsApi)
.service('MarketplacesOrdersAutoTransitionsApi', api.MarketplacesOrdersAutoTransitionsApi)
.service('MarketplacesOrdersBatchesApi', api.MarketplacesOrdersBatchesApi)
.service('MarketplacesOrdersExportsApi', api.MarketplacesOrdersExportsApi)
.service('MarketplacesOrdersGlobalApi', api.MarketplacesOrdersGlobalApi)
.service('MarketplacesOrdersListApi', api.MarketplacesOrdersListApi)
.service('MarketplacesOrdersOrderApi', api.MarketplacesOrdersOrderApi)
.service('PublicChannelsPublicChannelsApi', api.PublicChannelsPublicChannelsApi)
.service('PublicListOfValuesLOVApi', api.PublicListOfValuesLOVApi)
.service('PublicSecuritySecurityApi', api.PublicSecuritySecurityApi)
.service('UserListOfValuesLOVApi', api.UserListOfValuesLOVApi)

export default apiModule;
