/**
 * Catalogs
 * This API allows you to manage your catalogs
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Represent a catalog product
 */
export interface Product {
    "productId"?: models.BeezUPCommonProductId;
    "categoryId"?: models.BeezUPCommonCatalogCategoryId;
    "values"?: models.ProductValues;
}

