/**
 * Channel Catalogs
 * This api allows you to manage your channel catalogs.   A channel catalog is an association between your store and a channel.  You will be able to: - map your catalog colums to channel columns. - map your catalog categories to the channel categories and define a cost of this category - configure the general and cost settings of the channel - enable or disable a channel - exclude products using filters for a channel - override product values for a channel - disable or reenable a product on a channel 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Represents the general settings of your channel catalog
 */
export interface GeneralSettings {
    /**
     * If true then you authorize disclosure of my statistics generated from clicks and sales
     */
    "acceptToPublishInfo": boolean;
    /**
     * Activate bidding for this channel
     */
    "useBid": boolean;
    /**
     * Indicates that the channel authorize you to do not map your categories with their categories
     */
    "noCategoryMapping": boolean;
    /**
     * Do not export \"out of stock\" products. Note: this option is not taken into account by the counter. 
     */
    "doNotExportOutOfStockProducts": boolean;
    /**
     * Activate BeezUP tracking for my statistics (checked by default)
     */
    "activeBeezUPTracking": boolean;
}

