/**
 * Channel Catalogs
 * This api allows you to manage your channel catalogs.   A channel catalog is an association between your store and a channel.  You will be able to: - map your catalog colums to channel columns. - map your catalog categories to the channel categories and define a cost of this category - configure the general and cost settings of the channel - enable or disable a channel - exclude products using filters for a channel - override product values for a channel - disable or reenable a product on a channel 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GetChannelCatalogProductInfoListRequest {
    /**
     * Search by product sku. If null the filter will not be taken in account.
     */
    "sku"?: string;
    /**
     * Search by product title. If null the filter will not be taken in account.
     */
    "title"?: string;
    /**
     * Search overrided products. If null the filter will not be taken in account.
     */
    "overrided"?: boolean;
    /**
     * Search disabled products. If null the filter will not be taken in account.
     */
    "disabled"?: boolean;
    /**
     * Search product with category mapped with the channel. If null the filter will not be taken in account.
     */
    "categoryMapped"?: boolean;
    /**
     * Search excluded products by at least an exclusion filter. If null the filter will not be taken in account.
     */
    "excluded"?: boolean;
    /**
     * If false, search for product absent from the current catalog. If null the filter will not be taken in account.
     */
    "active"?: boolean;
}

