/**
 * Customer
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Internal usage: Old offer type. Describe the fix and variable model information
 */
export interface VariableModelInfo {
    /**
     * Click included with variable pricing information
     */
    "clickIncludedAndVariablePrices"?: Array<models.ClickIncludedAndVariablePrice>;
    /**
     * The overflow click count
     */
    "overflowClickCount"?: number;
    /**
     * The overflow click price
     */
    "overflowClickPrice"?: number;
}

