/**
 * Catalogs
 * This API allows you to manage your catalogs
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DetectedCatalogColumn {
    /**
     * IF true, the product values of this column will be not taken in account during the importation process
     */
    "ignored"?: boolean;
    "duplicateProductValueConfiguration"?: models.DuplicateProductValueConfiguration;
    "id": models.ColumnId;
    "catalogColumnName": models.CatalogColumnName;
    "userColumName": models.UserColumName;
    "configuration": models.ColumnConfiguration;
    "columnId": models.ColumnId;
    /**
     * Indicates if the column is detected or is from the current catalog
     */
    "detected": boolean;
    "existingConfiguration"?: models.ExistingCatalogColumnConfiguration;
}

