/**
 * Channels
 * This api allows you to get access to your channels
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ChannelInfoSalesContact {
    /**
     * Indicate the BeezUP offer
     */
    "name"?: string;
    /**
     * Indicate the sales contact email
     */
    "email"?: string;
    /**
     * The sales contact phone number
     */
    "phoneNumber"?: string;
}

