/**
 * Analytics
 * This API will help you to manage the tracking of your clicks and your sales, get reporting on this trackings and put in place rules based on this reporting to automatically optimize your channel catalogs. \\ Also, you will be able to consult the rule execution reporting. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * This update will replace the following values.
 */
export interface UpdateRuleRequest {
    /**
     * The name of the rule
     */
    "ruleName": string;
    /**
     * Not required. The start validity utc date of the rule.
     */
    "startUtcDate"?: Date;
    /**
     * Not required. The end validity utc date of the rule
     */
    "endUtcDate"?: Date;
}

