/**
 * Channels
 * This api allows you to get access to your channels
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ChannelInfoDetails {
    /**
     * The cost's description of the channel
     */
    "costs"?: string;
    /**
     * The business model of the channel
     */
    "businessModel"?: string;
    /**
     * The channel type
     */
    "channelType"?: string;
    /**
     * The channel category
     */
    "category"?: string;
    /**
     * The home url of the channel
     */
    "homeUrl"?: string;
    /**
     * The subscription link to the channel
     */
    "subscriptionLink"?: string;
}

