/**
 * Marketplaces - Orders
 * The features exposed in this API are centered around managing Orders harvested from your configured marketplaces.\\ This includes: - fetching current information (as known by BeezUP) for a single or multiple Orders, - requesting Order harvest to synchronize your marketplaces and BeezUP accounts, - changing BeezUP data and requesting changes to your marketplaces (accepting, shipping, etc), - configuring automatic changes to marketplace based our newly fetched data, - creating and exporting reports for your Orders. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The reporting related to a harvest order operation
 */
export interface HarvestOrderReporting {
    "executionUUID"?: models.ExecutionUUID;
    /**
     * The creation UTC date of the execution
     */
    "creationUtcDate"?: Date;
    /**
     * The processing status of the execution
     */
    "processingStatus"?: string;
    /**
     * The last update UTC date of the execution
     */
    "lastUpdateUtcDate"?: Date;
    /**
     * The warning message during the execution
     */
    "errorMessage"?: string;
    /**
     * The warning message during the execution
     */
    "warningMessage"?: string;
    "beezUPStatus"?: models.BeezUPOrderStatus;
    /**
     * The order marketplace status
     */
    "marketplaceStatus"?: string;
    /**
     * The marketplace order status forced by BeezUP during the order change oepration. This could happend when there is no status on the marketplace side.
     */
    "beezUPForcedStatus"?: string;
}

