/**
 * Analytics
 * This API will help you to manage the tracking of your clicks and your sales, get reporting on this trackings and put in place rules based on this reporting to automatically optimize your channel catalogs. \\ Also, you will be able to consult the rule execution reporting. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ReportByCategory {
    "catalogCategoryId": models.BeezUPCommonCatalogCategoryId;
    "catalogCategoryPath"?: models.BeezUPCommonCatalogCategoryPath;
    /**
     * The enabled product count for this category
     */
    "enabledProductCount": number;
    /**
     * The catalog product count related to this category
     */
    "catalogProductCount": number;
    /**
     * The click count for this category
     */
    "clickCount": number;
    /**
     * The cost for this category
     */
    "cost": number;
    /**
     * The order count for this category
     */
    "orderCount": number;
    /**
     * The Turnover for this category
     */
    "turnOver": number;
    /**
     * The margin for this category
     */
    "margin": number;
    /**
     * The performance indicator based on the performance indicator formula indicated in the request for this category
     */
    "performanceIndicator": number;
    "links"?: models.ReportByCategoryLinks;
}

