export * from './AccountApi';
import { AccountApi }  from './AccountApi';
export * from './AlertsApi';
import { AlertsApi }  from './AlertsApi';
export * from './AutoApi';
import { AutoApi }  from './AutoApi';
export * from './AutoTransitionsApi';
import { AutoTransitionsApi }  from './AutoTransitionsApi';
export * from './BatchesApi';
import { BatchesApi }  from './BatchesApi';
export * from './CatalogApi';
import { CatalogApi }  from './CatalogApi';
export * from './ChannelCatalogsCategoryMappingsApi';
import { ChannelCatalogsCategoryMappingsApi }  from './ChannelCatalogsCategoryMappingsApi';
export * from './ChannelCatalogsColumnMappingsApi';
import { ChannelCatalogsColumnMappingsApi }  from './ChannelCatalogsColumnMappingsApi';
export * from './ChannelCatalogsExclusionFiltersApi';
import { ChannelCatalogsExclusionFiltersApi }  from './ChannelCatalogsExclusionFiltersApi';
export * from './ChannelCatalogsGlobalApi';
import { ChannelCatalogsGlobalApi }  from './ChannelCatalogsGlobalApi';
export * from './ChannelCatalogsProductsApi';
import { ChannelCatalogsProductsApi }  from './ChannelCatalogsProductsApi';
export * from './ChannelCatalogsProductsOptimisationApi';
import { ChannelCatalogsProductsOptimisationApi }  from './ChannelCatalogsProductsOptimisationApi';
export * from './ChannelCatalogsProductsOverridesApi';
import { ChannelCatalogsProductsOverridesApi }  from './ChannelCatalogsProductsOverridesApi';
export * from './ChannelCatalogsSettingsApi';
import { ChannelCatalogsSettingsApi }  from './ChannelCatalogsSettingsApi';
export * from './ChannelsGlobalApi';
import { ChannelsGlobalApi }  from './ChannelsGlobalApi';
export * from './ContractsApi';
import { ContractsApi }  from './ContractsApi';
export * from './ExportsApi';
import { ExportsApi }  from './ExportsApi';
export * from './FriendsApi';
import { FriendsApi }  from './FriendsApi';
export * from './GlobalApi';
import { GlobalApi }  from './GlobalApi';
export * from './GroupsApi';
import { GroupsApi }  from './GroupsApi';
export * from './ImportationCatalogInfoApi';
import { ImportationCatalogInfoApi }  from './ImportationCatalogInfoApi';
export * from './ImportationProcessApi';
import { ImportationProcessApi }  from './ImportationProcessApi';
export * from './InvoicesApi';
import { InvoicesApi }  from './InvoicesApi';
export * from './LOVApi';
import { LOVApi }  from './LOVApi';
export * from './ListApi';
import { ListApi }  from './ListApi';
export * from './MarketplacesChannelCatalogsGlobalApi';
import { MarketplacesChannelCatalogsGlobalApi }  from './MarketplacesChannelCatalogsGlobalApi';
export * from './MarketplacesChannelCatalogsPublicationsApi';
import { MarketplacesChannelCatalogsPublicationsApi }  from './MarketplacesChannelCatalogsPublicationsApi';
export * from './MarketplacesChannelCatalogsSettingsApi';
import { MarketplacesChannelCatalogsSettingsApi }  from './MarketplacesChannelCatalogsSettingsApi';
export * from './OneOrderApi';
import { OneOrderApi }  from './OneOrderApi';
export * from './OptimisationsApi';
import { OptimisationsApi }  from './OptimisationsApi';
export * from './ReportsApi';
import { ReportsApi }  from './ReportsApi';
export * from './RightsApi';
import { RightsApi }  from './RightsApi';
export * from './RulesApi';
import { RulesApi }  from './RulesApi';
export * from './SecurityApi';
import { SecurityApi }  from './SecurityApi';
export * from './SharesApi';
import { SharesApi }  from './SharesApi';
export * from './StoresApi';
import { StoresApi }  from './StoresApi';
export * from './TrackingApi';
import { TrackingApi }  from './TrackingApi';
export const APIS = [ AccountApi, AlertsApi, AutoApi, AutoTransitionsApi, BatchesApi, CatalogApi, ChannelCatalogsCategoryMappingsApi, ChannelCatalogsColumnMappingsApi, ChannelCatalogsExclusionFiltersApi, ChannelCatalogsGlobalApi, ChannelCatalogsProductsApi, ChannelCatalogsProductsOptimisationApi, ChannelCatalogsProductsOverridesApi, ChannelCatalogsSettingsApi, ChannelsGlobalApi, ContractsApi, ExportsApi, FriendsApi, GlobalApi, GroupsApi, ImportationCatalogInfoApi, ImportationProcessApi, InvoicesApi, LOVApi, ListApi, MarketplacesChannelCatalogsGlobalApi, MarketplacesChannelCatalogsPublicationsApi, MarketplacesChannelCatalogsSettingsApi, OneOrderApi, OptimisationsApi, ReportsApi, RightsApi, RulesApi, SecurityApi, SharesApi, StoresApi, TrackingApi, ];
