export * from './AnalyticsOptimisationsApi';
import { AnalyticsOptimisationsApi }  from './AnalyticsOptimisationsApi';
export * from './AnalyticsReportsApi';
import { AnalyticsReportsApi }  from './AnalyticsReportsApi';
export * from './AnalyticsRulesApi';
import { AnalyticsRulesApi }  from './AnalyticsRulesApi';
export * from './AnalyticsTrackingApi';
import { AnalyticsTrackingApi }  from './AnalyticsTrackingApi';
export * from './CatalogsAutoApi';
import { CatalogsAutoApi }  from './CatalogsAutoApi';
export * from './CatalogsCatalogApi';
import { CatalogsCatalogApi }  from './CatalogsCatalogApi';
export * from './CatalogsGlobalApi';
import { CatalogsGlobalApi }  from './CatalogsGlobalApi';
export * from './CatalogsImportationCatalogInfoApi';
import { CatalogsImportationCatalogInfoApi }  from './CatalogsImportationCatalogInfoApi';
export * from './CatalogsImportationProcessApi';
import { CatalogsImportationProcessApi }  from './CatalogsImportationProcessApi';
export * from './ChannelCatalogsCategoryMappingsApi';
import { ChannelCatalogsCategoryMappingsApi }  from './ChannelCatalogsCategoryMappingsApi';
export * from './ChannelCatalogsColumnMappingsApi';
import { ChannelCatalogsColumnMappingsApi }  from './ChannelCatalogsColumnMappingsApi';
export * from './ChannelCatalogsExclusionFiltersApi';
import { ChannelCatalogsExclusionFiltersApi }  from './ChannelCatalogsExclusionFiltersApi';
export * from './ChannelCatalogsExportationsApi';
import { ChannelCatalogsExportationsApi }  from './ChannelCatalogsExportationsApi';
export * from './ChannelCatalogsGlobalApi';
import { ChannelCatalogsGlobalApi }  from './ChannelCatalogsGlobalApi';
export * from './ChannelCatalogsProductsApi';
import { ChannelCatalogsProductsApi }  from './ChannelCatalogsProductsApi';
export * from './ChannelCatalogsProductsOptimisationApi';
import { ChannelCatalogsProductsOptimisationApi }  from './ChannelCatalogsProductsOptimisationApi';
export * from './ChannelCatalogsProductsOverridesApi';
import { ChannelCatalogsProductsOverridesApi }  from './ChannelCatalogsProductsOverridesApi';
export * from './ChannelCatalogsSettingsApi';
import { ChannelCatalogsSettingsApi }  from './ChannelCatalogsSettingsApi';
export * from './ChannelsChannelsGlobalApi';
import { ChannelsChannelsGlobalApi }  from './ChannelsChannelsGlobalApi';
export * from './CustomerAccountApi';
import { CustomerAccountApi }  from './CustomerAccountApi';
export * from './CustomerAlertsApi';
import { CustomerAlertsApi }  from './CustomerAlertsApi';
export * from './CustomerContractsApi';
import { CustomerContractsApi }  from './CustomerContractsApi';
export * from './CustomerFriendsApi';
import { CustomerFriendsApi }  from './CustomerFriendsApi';
export * from './CustomerInvoicesApi';
import { CustomerInvoicesApi }  from './CustomerInvoicesApi';
export * from './CustomerRightsApi';
import { CustomerRightsApi }  from './CustomerRightsApi';
export * from './CustomerSecurityApi';
import { CustomerSecurityApi }  from './CustomerSecurityApi';
export * from './CustomerSharesApi';
import { CustomerSharesApi }  from './CustomerSharesApi';
export * from './CustomerStoresApi';
import { CustomerStoresApi }  from './CustomerStoresApi';
export * from './MarketplacesChannelCatalogsGlobalApi';
import { MarketplacesChannelCatalogsGlobalApi }  from './MarketplacesChannelCatalogsGlobalApi';
export * from './MarketplacesChannelCatalogsPublicationsApi';
import { MarketplacesChannelCatalogsPublicationsApi }  from './MarketplacesChannelCatalogsPublicationsApi';
export * from './MarketplacesChannelCatalogsSettingsApi';
import { MarketplacesChannelCatalogsSettingsApi }  from './MarketplacesChannelCatalogsSettingsApi';
export * from './MarketplacesOrdersAutoTransitionsApi';
import { MarketplacesOrdersAutoTransitionsApi }  from './MarketplacesOrdersAutoTransitionsApi';
export * from './MarketplacesOrdersBatchesApi';
import { MarketplacesOrdersBatchesApi }  from './MarketplacesOrdersBatchesApi';
export * from './MarketplacesOrdersExportsApi';
import { MarketplacesOrdersExportsApi }  from './MarketplacesOrdersExportsApi';
export * from './MarketplacesOrdersGlobalApi';
import { MarketplacesOrdersGlobalApi }  from './MarketplacesOrdersGlobalApi';
export * from './MarketplacesOrdersListApi';
import { MarketplacesOrdersListApi }  from './MarketplacesOrdersListApi';
export * from './MarketplacesOrdersOrderApi';
import { MarketplacesOrdersOrderApi }  from './MarketplacesOrdersOrderApi';
export * from './PublicChannelsPublicChannelsApi';
import { PublicChannelsPublicChannelsApi }  from './PublicChannelsPublicChannelsApi';
export * from './PublicListOfValuesLOVApi';
import { PublicListOfValuesLOVApi }  from './PublicListOfValuesLOVApi';
export * from './PublicSecuritySecurityApi';
import { PublicSecuritySecurityApi }  from './PublicSecuritySecurityApi';
export * from './UserListOfValuesLOVApi';
import { UserListOfValuesLOVApi }  from './UserListOfValuesLOVApi';
export const APIS = [ AnalyticsOptimisationsApi, AnalyticsReportsApi, AnalyticsRulesApi, AnalyticsTrackingApi, CatalogsAutoApi, CatalogsCatalogApi, CatalogsGlobalApi, CatalogsImportationCatalogInfoApi, CatalogsImportationProcessApi, ChannelCatalogsCategoryMappingsApi, ChannelCatalogsColumnMappingsApi, ChannelCatalogsExclusionFiltersApi, ChannelCatalogsExportationsApi, ChannelCatalogsGlobalApi, ChannelCatalogsProductsApi, ChannelCatalogsProductsOptimisationApi, ChannelCatalogsProductsOverridesApi, ChannelCatalogsSettingsApi, ChannelsChannelsGlobalApi, CustomerAccountApi, CustomerAlertsApi, CustomerContractsApi, CustomerFriendsApi, CustomerInvoicesApi, CustomerRightsApi, CustomerSecurityApi, CustomerSharesApi, CustomerStoresApi, MarketplacesChannelCatalogsGlobalApi, MarketplacesChannelCatalogsPublicationsApi, MarketplacesChannelCatalogsSettingsApi, MarketplacesOrdersAutoTransitionsApi, MarketplacesOrdersBatchesApi, MarketplacesOrdersExportsApi, MarketplacesOrdersGlobalApi, MarketplacesOrdersListApi, MarketplacesOrdersOrderApi, PublicChannelsPublicChannelsApi, PublicListOfValuesLOVApi, PublicSecuritySecurityApi, UserListOfValuesLOVApi, ];
