export * from './BeezUPApi';
import { BeezUPApi }  from './BeezUPApi';
export * from './GroupsApi';
import { GroupsApi }  from './GroupsApi';
export * from './LOVApi';
import { LOVApi }  from './LOVApi';
export * from './PublicChannelsApi';
import { PublicChannelsApi }  from './PublicChannelsApi';
export * from './SecurityApi';
import { SecurityApi }  from './SecurityApi';
export const APIS = [ BeezUPApi, GroupsApi, LOVApi, PublicChannelsApi, SecurityApi, ];
