/**
 * BeezUP API
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering */

export class V2UserMarketplacesChannelCatalogsApi {
    protected basePath = 'https://api.beezup.comv2';
    public defaultHeaders : any = {};

    static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

    constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
        if (basePath !== undefined) {
            this.basePath = basePath;
        }
    }

    /**
        * Get the marketplace properties for a channel catalog
        * 
        * @param channelCatalogId 
        */
    public getChannelCatalogMarketplaceProperties (channelCatalogId: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.ChannelCatalogMarketplaceProperties> {
        const localVarPath = this.basePath + '/v2/user/marketplaces/channelcatalogs/{channelCatalogId}/properties'
            .replace('{' + 'channelCatalogId' + '}', String(channelCatalogId));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'channelCatalogId' is not null or undefined
        if (channelCatalogId === null || channelCatalogId === undefined) {
            throw new Error('Required parameter channelCatalogId was null or undefined when calling getChannelCatalogMarketplaceProperties.');
        }
        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
        * Get the marketplace settings for a channel catalog
        * 
        * @param channelCatalogId Channel Catalog Id to query (required)
        */
    public getChannelCatalogMarketplaceSettings (channelCatalogId: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.ChannelCatalogMarketplaceSettings> {
        const localVarPath = this.basePath + '/v2/user/marketplaces/channelcatalogs/{channelCatalogId}/settings'
            .replace('{' + 'channelCatalogId' + '}', String(channelCatalogId));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'channelCatalogId' is not null or undefined
        if (channelCatalogId === null || channelCatalogId === undefined) {
            throw new Error('Required parameter channelCatalogId was null or undefined when calling getChannelCatalogMarketplaceSettings.');
        }
        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
        * Get  you marketplace channel catalog list
        * 
        */
    public getMarketplaceAccountStores (extraHttpRequestParams?: any ) : ng.IHttpPromise<models.MarketplaceChannelCatalogList> {
        const localVarPath = this.basePath + '/v2/user/marketplaces/channelcatalogs/';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
        * Fetch the publication history for an account, sorted by descending start date
        * 
        * @param marketplaceTechnicalCode Marketplace Technical Code to query (required)
        * @param accountId Account Id to query (required)
        * @param channelCatalogId Channel Catalog Id by which to filter (optional)
        * @param count Amount of entries to fetch (optional, default set to 10)
        * @param publicationTypes Publication types by which to filter (optional)
        */
    public getPublications (marketplaceTechnicalCode: string, accountId: number, channelCatalogId?: string, count?: number, publicationTypes?: Array<string>, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.AccountPublications> {
        const localVarPath = this.basePath + '/v2/user/marketplaces/channelcatalogs/publications/{marketplaceTechnicalCode}/{accountId}/history'
            .replace('{' + 'marketplaceTechnicalCode' + '}', String(marketplaceTechnicalCode))
            .replace('{' + 'accountId' + '}', String(accountId));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'marketplaceTechnicalCode' is not null or undefined
        if (marketplaceTechnicalCode === null || marketplaceTechnicalCode === undefined) {
            throw new Error('Required parameter marketplaceTechnicalCode was null or undefined when calling getPublications.');
        }
        // verify required parameter 'accountId' is not null or undefined
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling getPublications.');
        }
        if (channelCatalogId !== undefined) {
            queryParameters['channelCatalogId'] = channelCatalogId;
        }

        if (count !== undefined) {
            queryParameters['count'] = count;
        }

        if (publicationTypes !== undefined) {
            queryParameters['publicationTypes'] = publicationTypes;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
                                    params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
        * Save new marketplace settings for a channel catalog
        * Allow you to configure your marketplace settings.  Partial update accepted. 
        * @param channelCatalogId Channel Catalog Id to query
        * @param model Settings to save
        */
    public setChannelCatalogMarketplaceSettings (channelCatalogId: string, model: models.SetChannelCatalogMarketplaceSettingsRequest, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/v2/user/marketplaces/channelcatalogs/{channelCatalogId}/settings'
            .replace('{' + 'channelCatalogId' + '}', String(channelCatalogId));

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'channelCatalogId' is not null or undefined
        if (channelCatalogId === null || channelCatalogId === undefined) {
            throw new Error('Required parameter channelCatalogId was null or undefined when calling setChannelCatalogMarketplaceSettings.');
        }
        // verify required parameter 'model' is not null or undefined
        if (model === null || model === undefined) {
            throw new Error('Required parameter model was null or undefined when calling setChannelCatalogMarketplaceSettings.');
        }
        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: model,
                        params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
}
