export * from './AccountApi';
import { AccountApi }  from './AccountApi';
export * from './AlertsApi';
import { AlertsApi }  from './AlertsApi';
export * from './ContractsApi';
import { ContractsApi }  from './ContractsApi';
export * from './FriendsApi';
import { FriendsApi }  from './FriendsApi';
export * from './InvoicesApi';
import { InvoicesApi }  from './InvoicesApi';
export * from './RightsApi';
import { RightsApi }  from './RightsApi';
export * from './SecurityApi';
import { SecurityApi }  from './SecurityApi';
export * from './SharesApi';
import { SharesApi }  from './SharesApi';
export * from './StoresApi';
import { StoresApi }  from './StoresApi';
export const APIS = [ AccountApi, AlertsApi, ContractsApi, FriendsApi, InvoicesApi, RightsApi, SecurityApi, SharesApi, StoresApi, ];
